server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/admin-demo?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        slf4j:
          enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true